spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users?createDatabaseIfNotExist=true
    username: usr
    password: pwd

  liquibase:
    default-schema: users_schema
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: users_schema

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${USERS_DATASOURCE_URL}
    username: ${USERS_DATASOURCE_USERNAME}
    password: ${USERS_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false